---
title: "Analysis"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

```{r}
library(DT)
library(readr)
library(plotly)
library(htmltools)
library(tidyverse)
```


# Example Analysis #1

Last compiled: `r Sys.Date()` Example text.

## Second level header

Example text.

## Example R Analysis

```{r}
dataset <- readr::read_csv("data/data.csv")
```

### Example Interactive Table

```{r}
DT::datatable(dataset, 
              rownames = FALSE, 
              filter="top", 
              options = list(pageLength = 5, scrollX=T) )
```

### Example Plot #1

```{r}
plot1 <- dataset %>%
  dplyr::filter(Group==1) %>%
  ggplot2::ggplot(., aes(x = Month_Ordered, y = Variable_1)) +
  geom_bar(stat="identity") +
  geom_line() +
  geom_point()

plot1
```


### Example Dynamic Plot #1

```{r}
plotly::ggplotly(plot1)
```


### Example Plot #2

```{r}
dataset$Group<-as.factor(dataset$Group)

plot2<-dataset %>%
  ggplot(aes(x=Month_Ordered, y=Variable_2, group=Group, color=Group)) +
  geom_line() +
  geom_point()

plot2
```

### Example Dynamic Plot #2

```{r}
plotly::ggplotly(plot2)
```